{% set data = load_setup_py_data() %}

package:
  name: knoten
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/USGS-Astrogeology/knoten

build:
  number : {{ GIT_DESCRIBE_NUMBER }}
  string: dev
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

extra:
  channels:
    - conda-forge

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - csmapi
    - gdal
    - jinja
    - numpy
    - requests
    - scipy

test:
  imports:
    - knoten



