{% set data = load_setup_py_data() %}

package:
  name: knoten
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number : 0 
  string: dev
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

extra:
  channels:
    - conda-forge

requirements:
  build:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - csmapi
    - gdal
    - jinja2
    - numpy
    - requests
    - scipy

test:
  imports:
    - knoten



