{% set data = load_setup_py_data() %}

package:
  name: knoten
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/USGS-Astrogeology/knoten

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

extra:
  channels:
    - conda-forge
    - usgs-astrogeology

requirements:
  build:
  host:
    - pip
    - python
    - setuptools
  run:
    - ale>=0.3.2
    - python
    - csmapi>=1.0
    - gdal
    - jinja2
    - numpy
    - plio
    - pyproj
    - requests
    - scipy
    - shapely
    - usgscsm>=1.3.1

test:
  imports:
    - knoten



